mutation CreateProduct(
  $title: String!
  $amount: Int!
  $basePrice: Int!
  $currentPrice: Int
  # $preview: Upload!
  # $images: [String]
  # $tags: [String]
  $instock: Boolean!
  $gender: Gender!
  $mainTag: MainTag!
  $category: CategoryType!
  $features: ProductFeaturesInput!
  $description: String
) {
  createProduct(
    input: {
      title: $title
      amount: $amount
      basePrice: $basePrice
      currentPrice: $currentPrice
      # preview: $preview
      # images: $images
      # tags: $tags
      gender: $gender
      instock: $instock
      mainTag: $mainTag
      category: $category
      features: $features
      description: $description
    }
  ) {
    id
  }
}
