query getProductByID($id: ID!) {
  product(id: $id) {
    __typename
    ... on Product {
      id
      title
      amount
      basePrice
      currentPrice
      gender
      instock
      mainTag
      category
      description
      # preview: $preview
      # images: $images
      # tags: $tags
    }
    ... on NotFound {
      message
    }
  }
}
