query getProductByID($id: ID!) {
  product(id: $id) {
    __typename
    ... on Product {
      id
      title
      amount
      basePrice
      currentPrice
      gender
      instock
      isHidden
      mainTag
      category
      description
      preview
      # images: $images
      # tags: $tags
      features {
        material
        color
        gender
        category
      }
    }
    ... on NotFound {
      message
    }
  }
}
