query getProductByID($id: ID!) {
  product(id: $id) {
    __typename
    ... on Product {
      id
      title
      # amount: $amount
      basePrice
      currentPrice
      # preview: $preview
      # images: $images
      # tags: $tags
      gender
      instock
      mainTag
      # category # TODO: add on backend
      description
    }
    ... on NotFound {
      message
    }
  }
}
