mutation updateProduct(
  $id: ID!
  $title: String!
  $basePrice: Int!
  $currentPrice: Int
  $instock: Boolean!
  $description: String
) {
  updateProduct(
    input: {
      id: $id
      title: $title
      basePrice: $basePrice
      currentPrice: $currentPrice
      instock: $instock
      description: $description
    }
  ) {
    message
  }
}
